# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_13; end
module ::Anonymous_Delegator_14; end
module ::Anonymous_Delegator_18; end
module ::Rake::DSL; end
module ::Rake::TaskLib; end
module T::CompatibilityPatches::RSpecCompatibility::MethodDoubleExtensions; end
module T::CompatibilityPatches::RSpecCompatibility::RecorderExtensions; end
